<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <title><?php echo $RAML->title; ?>: <?php echo $RAML->getCurrentPath(); ?></title>
    <meta charset="utf-8">
    <base url="https://raml2html.local">

    <meta name="description" content="">
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="shortcut icon" href="img/favicon.png"> -->

    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet'>

    <!-- Syntax Highlighter -->
    <link rel="stylesheet" type="text/css" href="/templates/white-foot/syntax-highlighter/styles/shCore.css" media="all">
    <link rel="stylesheet" type="text/css" href="/templates/white-foot/syntax-highlighter/styles/shThemeDefault.css" media="all">

    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/templates/white-foot/css/font-awesome.min.css">
    <!-- Normalize/Reset CSS-->
    <link rel="stylesheet" href="/templates/white-foot/css/normalize.min.css">
    <!-- Main CSS-->
    <link rel="stylesheet" href="/templates/white-foot/css/main.css">

    <style>

    </style>

    <script type="text/javascript" src="/templates/white-foot/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="/templates/white-foot/js/jquery.nav.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/highlight.min.js"></script>

    <script>
        $(document).ready(function(){
            hljs.configure({useBR: true});

            $('code, div.apiresponse').each(function(i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>
</head>

<body id="welcome">

<aside class="left-sidebar">
    <div class="logo">
        <h1><a href="<?php echo $_SERVER['PHP_SELF']; ?>">
            <img src="/templates/white-foot/img/logo.png" alt="">&nbsp;<?php echo $RAML->get('title'); ?></a>
        </a></h1>
        <p>version <?php echo $RAML->get('version'); ?> <br> <?php echo $RAML->get('baseUri'); ?></p>
        <h4>
            Server Status:
            <?php
            $status = $RAML->pingStatus();
            if ($status == 'online'): ?>
                <span class="online">Online</span>
            <?php else: ?>
                <span class="offline">Offline</span>
            <?php endif; ?>

        </h4>
    </div>
    <nav class="left-nav">
        <?php
        include('_menu.phtml');
        ?>
    </nav>
</aside>

<div id="main-wrapper">
    <div class="main-content">
        <section id="article">

            <?php if ($RAML->getCurrentPath() != '/'): ?>
                <div class="content-header">
                    <h2><?php echo $RAML->getCurrentPath(); ?></h2>
                </div>

            <?php elseif (!$RAML->path()->description): ?>
                <!-- CSS HACK --><img width="1" height="1" />
            <?php endif; ?>


            <?php $validPath = $RAML->isPathValid($RAML->getCurrentPath()); ?>


            <?php if($validPath && !$RAML->getCurrentAction() && $RAML->path()->description):
                echo RAML2HTML\markdown::parse($RAML->path()->description);
            endif; ?>


            <?php
            if (!$validPath):
                include('_404.phtml');
            endif;
            ?>


            <?php
            if ($validPath && $RAML->path()->getVerbs() && !$RAML->getCurrentAction()):
                include('_verbs.phtml');
            endif;
            ?>



            <?php
            if ($validPath && $RAML->getChildPaths($RAML->getCurrentPath()) && !$RAML->getCurrentAction()):
                include('_resources.phtml');
            endif;
            ?>


            <?php
            if ($RAML->getCurrentAction()):
                include('_action.phtml');
                if ($disqus && $disqus_shortname):
                    include('_comments.phtml');
                endif;
            endif;
            ?>

        </section>

    </div>
</div>


<!-- Essential JavaScript Libraries
==============================================-->
<script type="text/javascript" src="/templates/white-foot/syntax-highlighter/scripts/shCore.js"></script>
<script type="text/javascript" src="/templates/white-foot/syntax-highlighter/scripts/shBrushXml.js"></script>
<script type="text/javascript" src="/templates/white-foot/syntax-highlighter/scripts/shBrushCss.js"></script>
<script type="text/javascript" src="/templates/white-foot/syntax-highlighter/scripts/shBrushJScript.js"></script>
<script type="text/javascript" src="/templates/white-foot/syntax-highlighter/scripts/shBrushPhp.js"></script>
<script type="text/javascript">SyntaxHighlighter.all()</script>
<script type="text/javascript" src="/templates/white-foot/js/custom.js"></script>
</body>
</html>
